# Generated by Django 4.2.1 on 2023-06-03 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerRequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_id', models.IntegerField()),
                ('pack1', models.TextField()),
                ('pack2', models.TextField()),
            ],
        ),
    ]
